include:
 - local: 'ci-templates.yml'
 - template: 'Security/SAST.gitlab-ci.yml'
 - template: 'Security/Dependency-Scanning.gitlab-ci.yml'
 - template: 'Security/Container-Scanning.gitlab-ci.yml'

stages:
 - pre-commit
 - test
 - build
 - security
 - push
 - deploy

variables:
 SERVICE_PATH: pitstop-customer
 SERVICE_NAME: pitstop-customer
 DOCKER_USERNAME: fatemzahra
 DOCKER_IMAGE: fatemzahra/pitstop-customer
 GITHUB_REPO: fatemzahrae/Customer-KubernetesFiles
 GITHUB_REPO_NAME: Customer-KubernetesFiles
 GITLAB_REPO: aseds6001802/customer-kubernetesfiles
 CS_DOCKERFILE_PATH: "pitstop-customer/Dockerfile" 
 #DOCKER_IMAGE: "registry.gitlab.com/aseds02/pitstop-customer/main"
#CS_IMAGE: "registry.gitlab.com/aseds02/pitstop-customer/main:$CI_COMMIT_SHORT_SHA"
 SECURE_LOG_LEVEL: "debug"

pre-commit:
 image: python:3.9
 stage: pre-commit
 before_script:
   - pip install pre-commit
 script:
   - pre-commit install
   - git config --global user.email "ci@bot.com"
   - git config --global user.name "CI Bot"
   - pre-commit run --all-files || (git add . && git commit -m "Fix pre-commit issues")
 rules:
   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"'



build:
 extends: .build-template
 stage: build


container_scanning:
  image: aquasec/trivy:0.44.0
  stage: security
  dependencies:
    - build
  services:
    - docker:dind
  script:
    - docker load < images/image.tar
    - trivy --version
    - trivy image ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA} \
        --format json \
        --output gl-container-scanning-report.json \
        --severity HIGH,CRITICAL \
        --exit-code 0
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
    paths:
      - gl-container-scanning-report.json
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


push:
 extends: .push-template
 stage: push
 needs:
   - container_scanning

deploy:
 extends: .deploy-template
 stage: deploy
 needs:
   - push
