include:
  - local: 'ci-templates.yml'

variables:
  SERVICE_PATH: pitstop-customer
  SERVICE_NAME: pitstop-customer
  DOCKER_USERNAME: fatemzahra
  DOCKER_IMAGE: fatemzahra/pitstop-customer
  GITHUB_REPO: fatemzahrae/Customer-KubernetesFiles
  GITHUB_REPO_NAME: Customer-KubernetesFiles
  GITLAB_REPO: aseds6001802/customer-kubernetesfiles
  
stages:
  - pre-commit
  - build
  - push
  - deploy


pre-commit:
  image: python:3.9
  stage: pre-commit
  before_script:
    - pip install pre-commit
  script:
    - pre-commit install
    - pre-commit run --all-files || (git add . && git commit -m "Fix pre-commit issues")
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"'


build:
  extends: .build-template
  needs:
    - pre-commit

sast:
  stage: build
  image: registry.gitlab.com/gitlab-org/security-products/analyzers/sast:latest
  artifacts:
    reports:
      sast: gl-sast-report.json
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

sca:
  stage: build
  image: registry.gitlab.com/gitlab-org/security-products/analyzers/dependency-scanning:latest
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


push:
  extends: .push-template
  needs:
    - build

container-security:
  stage: push
  image: anchore/scan-action:latest
  script:
    - anchore-cli image add ${DOCKER_IMAGE}:$CI_COMMIT_SHORT_SHA
    - anchore-cli image vuln ${DOCKER_IMAGE}:$CI_COMMIT_SHORT_SHA all
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


deploy:
  extends: .deploy-template
  needs:
    - push