include:
 - local: 'ci-templates.yml'
 - template: 'Security/SAST.gitlab-ci.yml'
 - template: 'Security/Dependency-Scanning.gitlab-ci.yml'
 - template: 'Security/Container-Scanning.gitlab-ci.yml'

stages:
 - pre-commit
 - test
 - build
 - security
 - push
 - deploy

variables:
 SERVICE_PATH: pitstop-customer
 SERVICE_NAME: pitstop-customer
 DOCKER_USERNAME: fatemzahra
 DOCKER_IMAGE: fatemzahra/pitstop-customer
 GITHUB_REPO: fatemzahrae/Customer-KubernetesFiles
 GITHUB_REPO_NAME: Customer-KubernetesFiles
 GITLAB_REPO: aseds6001802/customer-kubernetesfiles
 CS_DOCKERFILE_PATH: "pitstop-customer/Dockerfile" 
 #DOCKER_IMAGE: "registry.gitlab.com/aseds02/pitstop-customer/main"
#CS_IMAGE: "registry.gitlab.com/aseds02/pitstop-customer/main:$CI_COMMIT_SHORT_SHA"
 SECURE_LOG_LEVEL: "debug"

pre-commit:
 image: python:3.9
 stage: pre-commit
 before_script:
   - pip install pre-commit
 script:
   - pre-commit install
   - git config --global user.email "ci@bot.com"
   - git config --global user.name "CI Bot"
   - pre-commit run --all-files || (git add . && git commit -m "Fix pre-commit issues")
 rules:
   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"'



build:
 extends: .build-template
 stage: build



container-scan:
  stage: test
  image:
    name: snyk/snyk:docker
    entrypoint: [""]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:20.10.11-dind
  script:
    # Verify the tarball exists
    - ls -l images/image.tar
    # Load the image from the tarball
    - docker load < images/image.tar
    # List images to confirm successful loading
    - docker images
    # Authenticate with Snyk
    - snyk auth $SNYK_TOKEN
    # Get the loaded image ID
    - IMAGE_ID=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1)
    - snyk container test $IMAGE_ID --severity-threshold=high

  artifacts:
    paths:
      - snyk_report.json
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

push:
 extends: .push-template
 stage: push
 needs:
   - container_scanning

deploy:
 extends: .deploy-template
 stage: deploy
 needs:
   - push
