include:
 - local: 'ci-templates.yml'
 - template: 'Security/SAST.gitlab-ci.yml'
 - template: 'Security/Dependency-Scanning.gitlab-ci.yml'
 - template: 'Security/Container-Scanning.gitlab-ci.yml'

stages:
 - pre-commit
 - test
 - sca
 - build
 - security
 - push
 - deploy

variables:
 SERVICE_PATH: pitstop-customer
 SERVICE_NAME: pitstop-customer
 DOCKER_USERNAME: fatemzahra
 DOCKER_IMAGE: fatemzahra/pitstop-customer
 GITHUB_REPO: fatemzahrae/Customer-KubernetesFiles
 GITHUB_REPO_NAME: Customer-KubernetesFiles
 GITLAB_REPO: aseds6001802/customer-kubernetesfiles

pre-commit:
 image: python:3.9
 stage: pre-commit
 before_script:
   - pip install pre-commit
 script:
   - pre-commit install
   - git config --global user.email "ci@bot.com"
   - git config --global user.name "CI Bot"
   - pre-commit run --all-files || (git add . && git commit -m "Fix pre-commit issues")
 rules:
   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"'


dependency_scanning:
 stage: sca
 rules:
   - if: '$CI_COMMIT_BRANCH == "main"'

build:
 extends: .build-template
 stage: build
 needs:
   - dependency_scanning

container_scanning:
 stage: security
 needs:
   - build
 rules:
   - if: '$CI_COMMIT_BRANCH == "main"'

push:
 extends: .push-template
 stage: push
 needs:
   - container_scanning

deploy:
 extends: .deploy-template
 stage: deploy
 needs:
   - push
