include:
  - local: 'ci-templates.yml'

variables:
  SERVICE_PATH: pitstop-customer
  SERVICE_NAME: pitstop-customer
  DOCKER_USERNAME: fatemzahra
  DOCKER_IMAGE: fatemzahra/pitstop-customer
  GITHUB_REPO: fatemzahrae/Customer-KubernetesFiles
  GITHUB_REPO_NAME: Customer-KubernetesFiles
  GITLAB_REPO: aseds6001802/customer-kubernetesfiles
 
stages:
  - pre-commit
  - build
  - push
  - deploy

pre-commit:
  image: python:3.9
  stage: pre-commit
  before_script:
    - pip install pre-commit
  script:
    - pre-commit install
    - pre-commit run --all-files --hook-stage commit

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build:
  extends: .build-template
  needs:
    - pre-commit

push:
  extends: .push-template
  needs:
    - build

deploy:
  extends: .deploy-template
  needs:
    - push
