include:
  - local: ci-templates.yml

stages:
  - build
  - push
  - deploy

build:
  extends: .build-job-template
  variables: 
    DOCKER_IMAGE_NAME: "fatemzahra/pitstop-customer"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

push:
  extends: .push-job-template
  variables:
    DOCKER_IMAGE_NAME: "fatemzahra/pitstop-customer"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  needs:
    - build

deploy:
  extends: .deploy-job-template
  variables:
    DOCKER_IMAGE_NAME: "fatemzahra/pitstop-customer"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_MERGE_REQUEST_ID'
  needs:
    - push
