include:
  - local: 'ci-templates.yml'
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml


variables:
  SERVICE_PATH: pitstop-customer
  SERVICE_NAME: pitstop-customer
  DOCKER_USERNAME: fatemzahra
  DOCKER_IMAGE: fatemzahra/pitstop-customer
  GITHUB_REPO: fatemzahrae/Customer-KubernetesFiles
  GITHUB_REPO_NAME: Customer-KubernetesFiles
  GITLAB_REPO: aseds6001802/customer-kubernetesfiles
  
stages:
  - pre-commit
  - build
  - sast-scan
  - container-scan
  - push
  - deploy

pre-commit:
  image: python:3.9
  stage: pre-commit
  before_script:
    - pip install pre-commit
  script:
    - pre-commit install
    - git config --global user.email "ci@bot.com"
    - git config --global user.name "CI Bot"
    - pre-commit run --all-files || (git add . && git commit -m "Fix pre-commit issues")
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"'

build:
  extends: .build-template
  needs:
    - pre-commit


sast:
  stage: sast-scan
  script:
    - echo "Running SAST scan"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

sca:
  extends: dependency_scanning
  stage: sast-scan
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

container_security:
  extends: container_scanning
  stage: container-scan
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

push:
  extends: .push-template
  needs:
    - build 

deploy:
  extends: .deploy-template
  needs:
    - push