image: docker:latest
services:
    - docker:dind

stages:
  - build
  - push
  - deploy

build:
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd pitstop-customer 
    - docker build -t fatemzahra/pitstop-customer:$CI_COMMIT_SHORT_SHA . 
    - cd .. 
    - mkdir -p images
    - docker save fatemzahra/pitstop-customer:$CI_COMMIT_SHORT_SHA > images/image.tar
  artifacts:
    paths:
      - images/image.tar
    expire_in: 1 hour
  only:
    - main
    - merge_requests

push:
  stage: push
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "fatemzahra" --password-stdin
  script:
    - docker load < images/image.tar
    - docker push fatemzahra/pitstop-customer:$CI_COMMIT_SHORT_SHA
    - | 
      if [ "$CI_COMMIT_BRANCH" == "main" ]; then
        docker tag fatemzahra/pitstop-customer:$CI_COMMIT_SHORT_SHA fatemzahra/pitstop-customer:latest
        docker push fatemzahra/pitstop-customer:latest
      fi
  only:
    - main
    - merge_requests
  needs:
    - build 

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git curl
    - curl -sSL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    - chmod +x /usr/local/bin/yq
  script:
    - git config --global user.email "gitlab@example.com"
    - git config --global user.name "GitLab CI"
    - git clone https://oauth2:${GITHUB_TOKEN}@github.com/fatemzahrae/Customer-KubernetesFiles.git
    - cd Customer-KubernetesFiles/k8s
    - yq e -i '.spec.template.spec.containers[0].image = "fatemzahra/pitstop-customer:'$CI_COMMIT_SHORT_SHA'"' pitstop-customer-depl.yaml
    - git add .
    - git commit -m "Update image tag to $CI_COMMIT_SHORT_SHA [skip ci]"
    - git push https://oauth2:${GITHUB_TOKEN}@github.com/fatemzahrae/Customer-KubernetesFiles.git HEAD:main
  only:
    - main
  needs:
    - push
  variables:
    GIT_STRATEGY: clone
